### ISSUE TITLE
Panic in logging middleware during enrollment

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1645]
Doing some local development, it seems like I'm running into a panic that may have been introduced by #1635.

```
ts=2017-11-20T17:38:29.427255Z method=RequestEnrollment uuid=f6eed53a-bdb2-41e9-91a2-387879d14aa9 enrollSecret=MFyZh3+l1VUFNHE5Q3U9DLc6Xab1c6/C hostIdentifier=c255ee34-015e-4415-9d44-66caeeff647e errcode= reauth=false err=null took=2.508498ms
panic: interface conversion: interface {} is nil, not string

goroutine 727 [running]:
github.com/kolide/fleet/server/service.loggingMiddleware.EnrollAgent.func1(0x1c818a0, 0xc420266f60, 0x1c68ce0, 0xc420267110, 0x1c738a0, 0xc4213f01b0, 0xc4213bd430, 0xbe7ce2a559521de0, 0x40504bbea, 0x22f7cc0)
	/Users/marpaia/go/src/github.com/kolide/fleet/server/service/logging_osquery.go:21 +0x3a5
github.com/kolide/fleet/server/service.loggingMiddleware.EnrollAgent(0x1c818a0, 0xc420266f60, 0x1c68ce0, 0xc420267110, 0x1c738a0, 0xc4213f01b0, 0xc4216c21e0, 0x20, 0xc4204da480, 0x24, ...)
	/Users/marpaia/go/src/github.com/kolide/fleet/server/service/logging_osquery.go:28 +0x1b1
github.com/kolide/fleet/server/service.(*loggingMiddleware).EnrollAgent(0xc4202a0040, 0x1c738a0, 0xc4213f01b0, 0xc4216c21e0, 0x20, 0xc4204da480, 0x24, 0xc42049c780, 0xc4214d4160, 0xc4213bd578, ...)
	<autogenerated>:1 +0xb4
github.com/kolide/fleet/server/service.(*metricsMiddleware).EnrollAgent(0xc420267140, 0x1c738a0, 0xc4213f01b0, 0xc4216c21e0, 0x20, 0xc4204da480, 0x24, 0xc4213bd5c0, 0x80, 0x1698ac0, ...)
	<autogenerated>:1 +0x8f
```

**Comment by zwass** [comment]
Closing this as it looks like it has been resolved by the revert.
