### ISSUE TITLE
Fleet fails to start (likely due to database config)

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#1968]
### What version of `fleet` are you using (`fleet version --full`)?
I am using the `kolide/fleet:2.0.0` docker container.

### What operating system are you using?
I am using the `kolide/fleet:2.0.0` docker container.

### What did you do?
I am seeing errors starting fleet and running the migrations. I suspect this is related to the database, but I can't figure out what's upsetting fleet from the stack trace.

So, my DBAs don't want to grant the fleet user the `ALTER TABLE` permission, only read/write. So, we have copied the schema from the staging instance where this is not a concern and also copied the `migration_status_tables` as we figured that would tell the migrations that changed the schema not to run, but let the data migrations still run. (Which in hindsight sounds like a great way to mess up data migrations...)

So, I guess I'm looking for two things.
1. Is there a suggested way for me to deploy Fleet in an environment like this?
1. Help understanding the stack trace :point_down: 

### What did you expect to see?
I expected `fleet` to start successfully.

### What did you see instead?
```
2018-12-18T15:15:57.642406535Z panic: unreachable

2018-12-18T15:15:57.642465113Z
2018-12-18T15:15:57.64247099Z goroutine 1 [running]:

2018-12-18T15:15:57.642475698Z github.com/kolide/fleet/vendor/github.com/kolide/goose.(*Client).GetDBVersion(0xc000170100, 0xc0002640c0, 0x0, 0x0, 0x0)

2018-12-18T15:15:57.642481393Z /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/kolide/goose/migrate.go:208 +0x35c

2018-12-18T15:15:57.642486453Z github.com/kolide/fleet/server/datastore/mysql.(*Datastore).MigrationStatus(0xc000173ba0, 0x27, 0xc000034076, 0xf)

2018-12-18T15:15:57.642491337Z /Users/marpaia/go/src/github.com/kolide/fleet/server/datastore/mysql/mysql.go:144 +0xf0

2018-12-18T15:15:57.642496131Z main.createPrepareCmd.func2(0xc000214a00, 0x1d95378, 0x0, 0x0)

2018-12-18T15:15:57.642500707Z /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleet/prepare.go:47 +0x132

2018-12-18T15:15:57.642516606Z github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).execute(0xc000214a00, 0x1d95378, 0x0, 0x0, 0xc000214a00, 0x1d95378)

2018-12-18T15:15:57.642522877Z /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:760 +0x2cc

2018-12-18T15:15:57.642527828Z github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000214500, 0x1e, 0x0, 0xc000215400)

2018-12-18T15:15:57.642532778Z /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:846 +0x2fd

2018-12-18T15:15:57.642537558Z github.com/kolide/fleet/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000214500, 0xc000145f50, 0x1)

2018-12-18T15:15:57.642542353Z /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/spf13/cobra/command.go:794 +0x2b

2018-12-18T15:15:57.642547247Z main.main()

2018-12-18T15:15:57.642551781Z /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleet/main.go:29 +0x1cd
```

**Comment by groob** [comment]
https://github.com/kolide/goose/blob/7aebd1deb5abbf22308aae6c55eac771f4c6bd35/migrate.go#L208

Looks like you're getting no rows when you run this query:

https://github.com/kolide/goose/blob/7aebd1deb5abbf22308aae6c55eac771f4c6bd35/dialect.go#L89

Can you run the same query manually in your db?

**Comment by crimsonknave** [comment]
The `migrations_status_data` table was empty. Adding an id 0 item (to match the first entry in the staging database) fixed the issue.
